development:
  adapter: mysql2
  encoding: utf8
  database: live_inventory_development
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: live_inventory_live
  pool: 5
  username: root
  password: risingnow1436
  socket: /var/run/mysqld/mysqld.sock